# Generated by Django 6.0.4 on 2026-04-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_simplify_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("auth_date", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-transaction_date", "-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="tracker_tra_telegra_e52652_idx",
            old_name="tracker_tran_telegramid_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="tracker_tra_telegra_c1526f_idx",
            old_name="tracker_tran_type_idx",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category_name",
            field=models.CharField(default="Other", max_length=100),
        ),
    ]
