# Generated by Django 6.0.4 on 2026-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_otpsession_telegramuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount_khr",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("KHR", "Cambodian Riel")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
