# Generated by Django 6.0.4 on 2026-04-19 15:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="conversation_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["telegram_id", "conversation_id"],
                name="tracker_cha_telegra_9f88a8_idx",
            ),
        ),
    ]
