# Generated by Django 6.0.4 on 2026-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_chatmessage_conversation_id_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="transaction_amount_gt_zero"
            ),
        ),
    ]
